name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v ./
    - name: Install
      run: go install -v ./
    - name: Test
      run: go test -v -coverprofile coverage.txt -covermode=atomic ./...
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.txt
        fail_ci_if_error: true
